### ISSUE TITLE
Short read data compatibility 

### ISSUE THREAD

**Issue by JannahS** [PacificBiosciences/trgt#11]
Hi there,

Can I use trgt to call repeat expansions from short read data (illlumina data for example) ? If yes, is there any caveat?

Thanks in advance.

**Comment by hdashnow** [comment]
Depending on your specific variant types/project goals, a few tools you might look at are: GangSTR, STRling, HipSTR, ExpansionHunter, ExpansionHunter Denovo

**Comment by atimmaraju** [comment]
Hello,

Is TRGT compatible with amplicons (~200bp) sequenced on pacbio, with the hifi reads aligned with BWA? 

Thanks,
Arun

**Comment by egor-dolzhenko** [comment]
Hi Arun,

Thanks for reaching out. Would you be open to sharing some details of your assay? This would help us to provide concrete suggesitons. Please feel free to reach out by [email](mailto:edolzhenko@pacificbiosciences.com).

Best wishes,
Egor
