### ISSUE TITLE
runtime error (thread '<unnamed>' panicked at 'called `Result::unwrap()`)

### ISSUE THREAD

**Issue by splaisan** [PacificBiosciences/trgt#15]
HI,
I am trying to run TRGT on PacBio HiFi pbmm2 read mappings for HG002 (works with the example data)
I get the following error:

```
ubuntu 22
trgt 0.5.0-a70fa16
```

```
$ trgt --genome pbmm2ref/hg38.fa --repeats /data/biodata/TRGT_data/polymorphic_repeats.hg38.bed --reads mappings/pbmm2_hg38_mappings.bam --output-prefix HG002
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: ParseIntError { kind: InvalidDigit }', src/locate/read.rs:83:37
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: ParseIntError { kind: InvalidDigit }', src/locate/read.rs:83:37
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: ParseIntError { kind: InvalidDigit }', src/locate/read.rs:83:37
...
```

I tried specifying the thread # but does not help

```
$ trgt --genome pbmm2ref/hg38.fa --repeats /data/biodata/TRGT_data/polymorphic_repeats.hg38.bed --reads mappings/pbmm2_hg38_mappings.bam --output-prefix HG002 --threads 1
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: ParseIntError { kind: InvalidDigit }', src/locate/read.rs:83:37
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: ParseIntError { kind: InvalidDigit }', src/locate/read.rs:83:37
thread '<unnamed>' panicked at 'called `Result::unwrap()` on an `Err` value: ParseIntError { kind: InvalidDigit }', src/locate/read.rs:83:37
...
```

I suspect that the error ascii codes of HiFi mappings are not making TRGT happy but have little clue about it.

I attach few reads in sam format for debug

[sample.sam.zip](https://github.com/PacificBiosciences/trgt/files/12845063/sample.sam.zip)

**Comment by egor-dolzhenko** [comment]
Hi Stephane. Apologies about the issue and thank you very much for a detailed bug report.

The issue appears to be caused by the MM tag (it looks like methylation was called twice as there are two occurrences of the "C+m" field inside the MM tag). We will update TRGT to only use the most recent set of methylation calls if methylation was called multiple times. Additionally, it might be worth it to trace the source of the duplicated calls and adjust the analysis pipeline accordingly.

**Comment by splaisan** [comment]
Thanks @egor-dolzhenko 
It is my first time analysing methylation and I am the source of duplication, I followed the online tutorial for jasmine and apparently the methylation info was already there from the SequelIIe run itself.
I will try redoing it without the jasmine step to see if your command works better.
thanks for your kind suppport

**Comment by egor-dolzhenko** [comment]
Thank you @splaisan -- this sounds good

**Comment by splaisan** [comment]
HI Egor,
It ran smoothly after remapping the reads without jasmine step and running your tool on these mappings.
Thanks for your help

**Comment by egor-dolzhenko** [comment]
Glad to hear it, Stephane! Please let me know if I can help with anything else
