### ISSUE TITLE
VCF Header Columns sample_id

### ISSUE THREAD

**Issue by themkdemiiir** [PacificBiosciences/trgt#18]
Hey,
I am facing an issue while using Hiphase for the vcfs I generated. The sample ID of the trgt vcf does not match the ones I generated. Upon further investigation, I found that trgt does not take the basename of the bam file but instead takes what appears before the '.bam'. Can you help me with this?

TRGT output vcf
```
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  NA17282.HomoSapiens.aligned
```
PBSV output vcf
```
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  NA17282
```
DEEPVARIANT output vcf
```
#CHROM  POS     ID      REF     ALT     QUAL    FILTER  INFO    FORMAT  NA17282
```

**Comment by egor-dolzhenko** [comment]
Apologies about the issue. We will change how the sample name is set in an upcoming release of TRGT. Meanwhile, I have attached binaries of the development version of TRGT where this is already implemented.

[trvz-v0.6.1-fix-sample-name-linux_x86_64.gz](https://github.com/PacificBiosciences/trgt/files/13444189/trvz-v0.6.1-fix-sample-name-linux_x86_64.gz)
[trgt-v0.6.1-fix-sample-name-linux_x86_64.gz](https://github.com/PacificBiosciences/trgt/files/13444187/trgt-v0.6.1-fix-sample-name-linux_x86_64.gz)

Best wishes,
Egor

**Comment by themkdemiiir** [comment]
Thanks for the update! When will you update the docker image in quay.io?

**Comment by egor-dolzhenko** [comment]
Of course! And could you please share a link to the docker image in question?

**Comment by themkdemiiir** [comment]
I'm sorry for not getting back to you sooner. Thanks for the help. I appreciate it.
the link: https://quay.io/repository/pacbio/trgt?tab=tags

**Comment by egor-dolzhenko** [comment]
Thanks! I am assuming that these images get created automatically once TRGT is updated on bioconda. If this is the case, you should get a new image shortly after we release the next version of TRGT 👍

**Comment by egor-dolzhenko** [comment]
@themkdemiiir Please note that we just released a new version TRGT with better handling of sample names. Also @williamrowell updated the docker image on quay.io (I incorrectly assumed that this image will be updated automatically). Please feel free to reopen the issue if needed.
