### ISSUE TITLE
thread 'main' panicked at 'called `Option::unwrap()`

### ISSUE THREAD

**Issue by asuresh2** [PacificBiosciences/trgt#2]
Hello,

I'm trying to run TRGT on some bam files that I have. It run just fine on most of them. But for a few of them I'm getting the following error:
`thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /root/.cargo/registry/src/github.com-1ecc6299db9ec823/rust-htslib-0.38.2/src/bam/header.rs:88:49
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace`

I checked the input files to make sure the paths are the right as well. Any ideas on what might be happening?

Thanks!

**Comment by egor-dolzhenko** [comment]
Hi Abhilash. Apologies about the error. Would you be open to sharing a small slice of your BAM file? Please feel free to email me at edolzhenko@pacificbiosciences.com.

**Comment by asuresh2** [comment]
Hello!

We were actually able to figure out the issue, it the bam files were subreads instead of CCS reads.
Thank you!

**Comment by egor-dolzhenko** [comment]
@asuresh2, glad you were able to resolve the issue! We will make sure that next time TRGT will output a meaningful error message in this situation. Please let us know if you have any further feedback.
