### ISSUE TITLE
TRVZ v0.8.0 hmm error on some repeats

### ISSUE THREAD

**Issue by zbonnstetter** [PacificBiosciences/trgt#27]
I'm encountering the following error after updating to the newest version:
> thread 'main' panicked at src/hmm/builder.rs:182:14:
Encountered unknown base 78
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

When I try to use TRVZ to visualize these repeats:
>HOXD13
FOXL2
PHOX2B
RUNX2
HOXA13
PRDM12 *
ZIC2
ZFHX3 *
SOX3

The two I've marked with asterisks are repeats I've added to my own catalog that I figured I would mention for the sake of being thorough. I do have additional custom entries in my catalog that are not throwing this error, however, and it is the same repeats giving this error for every sample I've tested.

**Comment by egor-dolzhenko** [comment]
Thanks for catching this, Zach. I confirm that this is a TRVZ bug. It will be fixed in the next release in a few weeks (led by @tmokveld). Meanwhile, a temporary fix is to replace `N`s in the motif sequence with any base symbol.

**Comment by egor-dolzhenko** [comment]
@zbonnstetter, we decided to release the fix now instead of waiting until the v1.0.0 release. Can I send you the binary for testing ahead of the release?

**Comment by zbonnstetter** [comment]
@egor-dolzhenko of course, once I receive it I'll give it a test and get back to you right away.

**Comment by egor-dolzhenko** [comment]
@zbonnstetter Thank you -- the binaries are attached!
[trgt-v0.9.0-linux_x86_64.gz](https://github.com/PacificBiosciences/trgt/files/14892036/trgt-v0.9.0-linux_x86_64.gz)
[trvz-v0.9.0-linux_x86_64.gz](https://github.com/PacificBiosciences/trgt/files/14892038/trvz-v0.9.0-linux_x86_64.gz)

**Comment by zbonnstetter** [comment]
@egor-dolzhenko I tested both binaries on a few samples and can confirm I'm no longer getting that error, and at a glance all output is present and looks good. If I do happen to notice anything else I will reach out. Thank you for your swift responses!

**Comment by egor-dolzhenko** [comment]
Excellent -- thank you very much @zbonnstetter!
