### ISSUE TITLE
Repeats

### ISSUE THREAD

**Issue by hchetia** [PacificBiosciences/trgt#3]
Hi Egor @egor-dolzhenko 
Congrats on yet another repeat hunting tool, now for long reads!
I had a query about the reference repeat files here- https://github.com/PacificBiosciences/trgt/tree/main/repeats
Are the repeats in **trgt/repeat_catalog.hg38.bed** same as that in https://github.com/Illumina/RepeatCatalogs/tree/master/hg38/variant_catalog.json?

Best,
Hasna

**Comment by egor-dolzhenko** [comment]
Thank you Hasna! Yes, the repeats should be the same. We'd like to create multiple sets of repeat definitions for TRGT that correspond to well-known repeat catalogs. To this end, we also created a set of repeat definitions based on this resource: https://zenodo.org/record/7013709#.Yz5NtezMJAc. I can share it with you if this may be helpful for you work.

**Comment by hchetia** [comment]
Thanks, Egor, that will be lovely. Can I download it from Zenodo? If not, my email ID is hchetia@rockefeller.edu.
