### ISSUE TITLE
Recommended repeat definition file to use

### ISSUE THREAD

**Issue by gevro** [PacificBiosciences/trgt#34]
Hi,
You link to a zenodo repository with repeat definition files - which do you recommend to use?

https://zenodo.org/records/8329210

**Comment by egor-dolzhenko** [comment]
Thanks for the question! I would recommend using these two catalogs:
- the genome-wide repeat catalog ([adotto_repeats.hg38.bed.gz](https://zenodo.org/records/8329210/files/adotto_repeats.hg38.bed.gz?download=1)) and
- the catalog with known pathogenic repeats from [STRchive](https://strchive.org/) (the corresponding catalog from the Zenodo repository is a smaller and less carefully curated version of whats in STRchive).

Once you genotype known pathogenic repeats with TRGT, you can use a tool like [TRexs](https://github.com/PacificBiosciences/TRexs) to check if any of your samples contain a pathogenic expansion. Note that other tools like TRexs may be released in the near future. If you genotype repeats from the genome-wide catalog in a family trio, you can use the newly developed tool [TRGT-denovo](https://github.com/PacificBiosciences/trgt-denovo) to find *de novo* mutations in repeat regions.

I hope this helps. Please let us know if you have any other questions.

**Comment by gevro** [comment]
Thanks! Should the catalogs be combined, or each run separately?

**Comment by egor-dolzhenko** [comment]
Totally up to you. Many users analyze known pathogenic repeats separately from the rest of the repeats and hence keep the catalogs separate.
