### ISSUE TITLE
update bioconda package

### ISSUE THREAD

**Issue by fo40225** [PacificBiosciences/trgt#35]
TRGT released version v1.1.0 on 2024-07-17, but the latest version on bioconda is still 0.9.0-0

Please help to update.

Thanks.

https://github.com/PacificBiosciences/trgt/releases/

https://bioconda.github.io/recipes/trgt/README.html

https://github.com/PacificBiosciences/pbbioconda/issues/702

**Comment by tmokveld** [comment]
@fo40225 The latest TRGT version is now on Bioconda (https://anaconda.org/bioconda/trgt) and should now automatically bump versions as they are released here.
