### ISSUE TITLE
CLI flag to disable spanning reads BAM generation

### ISSUE THREAD

**Issue by SHuang-Broad** [PacificBiosciences/trgt#36]
Hi,

We have some high number of samples to process through, and writing these spanning reads all the time incurs some costs that we hope to optimize away.

These costs could include cycles spent on outputting the spanning reads for all (?) sites, especially for larger catalogs.

So we wonder if the CLI could expose a flag to disable the spanning reads BAM generation. Then we can run TRGT again in sites where we really need to dig in.

Thank you,
Steve

**Comment by egor-dolzhenko** [comment]
Hi Steve. Sure, we can totally do this. We'll benchmark the corresponding runtime improvement and get back to you soon.

**Comment by tmokveld** [comment]
Hi Steve. I had a look at this, disabling BAM writing saves approximately 25% runtime (100x at 32 threads). 

If you are interested in testing this, I attached a TRGT v1.1.1 binary that adds the `--disable-bam-output` flag: [trgt-v1.1.1-nobam-x86_64-unknown-linux-gnu.tar.gz](https://github.com/user-attachments/files/16557808/trgt-v1.1.1-nobam-x86_64-unknown-linux-gnu.tar.gz)

This flag will be added in an upcoming release.

**Comment by tmokveld** [comment]
This flag is in [TRGT v1.2.0](https://github.com/PacificBiosciences/trgt/releases/tag/v1.2.0).
