### ISSUE TITLE
about the process method of adotto TR annotation file

### ISSUE THREAD

**Issue by WeiCSong** [PacificBiosciences/trgt#37]
Hi, 
the adotto paper (nat biotech 2024) mentioned a total of 1.7m TR loci in hg38, whereas the adotto_hg38 bed file in TRGT tutorial has about 0.9m rows, is there any preprocess and filter step between them? Thanks for your help!

**Comment by egor-dolzhenko** [comment]
Thanks for the question! In the paper describing TRGT we used an older version of the Adotto repeat catalog. Here is a link to [the version 1.0 of the Adotto catalog](https://zuchnerlab.s3.amazonaws.com/RepeatExpansions/TRGT/adotto_TRregions_TRGTFormatWithFlankingSeq_v1.0.bed.gz) from @ACEnglish adapted for TRGT by @mdanzi.
