### ISSUE TITLE
Soft-clipped reads in genome alignment are discarded

### ISSUE THREAD

**Issue by MaestSi** [PacificBiosciences/trgt#38]
Dear developers,
I aligned my PacBio Hi-Fi reads to the reference genome with:
`minimap2 -ax map-hifi -y --MD -Y -t 24 <reference.fasta> <reads.fastq> | samtools view -h | samtools sort -o <sample.bam>`
I then ran `trgt genotype` and `trgt plot` and, based on both the content of <sample.spanning.bam> and the plots, it looks like most of my expanded reads, which show soft-clipping in the alignment, are discarded. Is there a way I can recover them, aside from changing the reference genome?
Best,
SM

**Comment by egor-dolzhenko** [comment]
Thanks for reporting the issue. We would be happy to take a look. Would you be open to sharing a slice of your BAM file with reads containing the problematic repeat region? If yes, please feel free to reach out by [email](mailto:edolzhenko@pacificbiosciences.com).

By the way, we recommend aligning your HiFi reads with [pbmm2](https://github.com/PacificBiosciences/pbmm2).

**Comment by MaestSi** [comment]
Hi, I just tested pbmm2, but I found no differences compared to minimap2.
I'll discuss with my bosses about the possibility of sharing the data after the holidays.
Thanks in advance,
SM

**Comment by egor-dolzhenko** [comment]
Good to know, thanks! In general, soft clipping by itself should not cause analysis problems, but it could be a symptom of a larger issue. Are you analyzing known pathogenic repeats in HiFi WGS data?

**Comment by MaestSi** [comment]
Yes, I'm analyzing known pathogenic repeats, but not with WGS data. We used PacBio PureTarget instead.
Do you recall any available examples of soft-clipped reads being analysed by TRGT, so that I can have a look at parameters used in that case?
Thanks,
SM

**Comment by egor-dolzhenko** [comment]
Could you please try the following PureTarget-specific parameters which were originally defined by @pbsena?

```
pbmm2 align -N 1 --sort --preset HIFI hg38.fa unmapped.bam mapped.bam

trgt --genotyper=cluster \
       --min-read-quality=-1.0 \
       --max-depth=10000 \
       --aln-scoring=1,1,0,1,1,200 \
       --min-flank-id-frac=0.7 \
       --flank-len=200 \
       --output-flank-len=200 \
       --genome=hg38.fa \
       --repeats=repeats.bed \
       --reads=mapped.bam \
       --output-prefix=sample
```

**Comment by MaestSi** [comment]
Hi, I tested the command you provided. Still, the maximum repeat length I see plotted by tgrt is much shorter than the repeat length I see in some of the soft-clipped reads of the alignment.
Best,
SM

**Comment by egor-dolzhenko** [comment]
Thanks for confirming. Hopefully we will have an opportunity to evaluate this repeat on our end.

Also, when you visualized alignments with TRGT, have you tried making waterfall plots (`--plot-type waterfall`)? The default `allele` plots show alignments of reads to the consensus allele sequences, which may be much shorter than some of the reads for mosaic repeat expansions.

**Comment by MaestSi** [comment]
Hi,
indeed it seems the waterfall plot solved the issue, thank you.
This was the plot I obtained with my tool [MosaicViewer](https://github.com/MaestSi/MosaicViewer_CNBP), which was originally developed for ONT noisy data.

Based on these results, I was expecting to see `CCTG`, `TCTG` and `CCCG` motifs on the gene (-) strand, corresponding to `CAGG`, `CAGA` and `CGGG` on the (+) strand, respectively.
Unexpectedly, the allele plot only showed `CAGG` ( = `revComp of CCTG`) motif, and the longest repeats were about 1600*4 = 6400 bp, rather than the expected 22 kbp. While, when I look at the waterfall plot, also `CAGA` (= `revComp of TCTG`) motif appears.


Possibly, those reads with `CAGA` motif did not align to the consensus sequence, right?
Also, would it be possible to show the repeats lengths in the waterfall plot?
As for the repeat definition file, I used `pathogenic_repeats_hg38.bed`, that for CNBP reports the following:
`ID=CNBP;MOTIFS=CAGG,CAGA,CA;STRUC=<CNBP>`
So, I assume this is the reason why `CGGG` is not reported in the waterfall plot. Would it be easy to add it?
Thanks in advance,
SM

**Comment by egor-dolzhenko** [comment]
Good to know about MosaicViewer! I wasn't aware of your tool. To answer your questions: Yes, it seems difficult to define a meaningful consensus sequence for highly mosaic repeats. So TRGT essentially uses a sequence of a read whose length is close to the middle of the read length distribution. This has significant tradeoffs like the one you see here. And yes, to include the `CGGG` motif into the analysis, you can just edit the repeat definition file and add the missing motif there.

We are currently working on a major refactor of the visualization algorithm. In particular, we will add the size scale and better motif identification to the waterfall plots in one of the upcoming releases. Hopefully in 2-4 weeks.

Thank you for the super helpful feedback!

**Comment by MaestSi** [comment]
Hi, I confirm that adding the `CGGG` motif identified it in the reads, as expected.
Thank you very much for your very prompt feedback and help.
Looking forward to trying out the new version!
Best,
SM

**Comment by egor-dolzhenko** [comment]
Glad to hear it, thank you! We will try to release the new version of the plotting algorithm soon.
