### ISSUE TITLE
rust panic byte index

### ISSUE THREAD

**Issue by ljmills** [PacificBiosciences/trgt#4]
I am using TRGT on BAM aligned with pbmm2 and for some of my files I am getting errors like this 

thread '<unnamed>' panicked at 'byte index 18665 is out of bounds of `AACTAAATATCCATCAACAGGAGAATGGATAAACAAACTGTGGCATATTCATATAATGAAATACTACTCAGTAAGGAAAAGGATGAATTATTGACTTTCGGAACACGCGTTAATCAGAATAATCATGCTGAGTGAAGGAAGGCAGTGTATTTTATGTAATTCCACTTATATAAAATTCTAGAAAATACAATCTAATCCATAGTGTGAGAAAGGAGATGAGAGGTTGCCTGGGGATGAACAGGAGCATGAAAGGTGG`[...]', library/core/src/str/mod.rs:107:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

another example

thread '<unnamed>' panicked at 'byte index 18446744073709551614 is out of bounds of `TGTGGCTTAGCATTCCAGCCTGGGTGACAAGAGCAAAACTCTGTCTCAAAATAAATAAATAAATAAATAAATAAATAAATAAATAAATTAATAAATAAATAAAATGTCCTCATGAAACACCTGTGGCTTAGCAGGAAGTTGGAAGCTAAAGAAGTGACCAGCGCCTGGAGTTTGGCTCCTGGCTGAATCCACATGGGCTCTTTGGTTCTTTCTTTCTTTCCCTGGAATAAGGATTCAAGGAGAATTTCTCCAATAG`[...]', library/core/src/str/mod.rs:107:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Command I ran
/home/ljmills/shared/bin/trgt-v0.3.2-linux_x86_64 --genome /home/ljmills/shared/hg38_clean/seq/hg38_clean.fa --repeats /home/ljmills/ljmills/pacBio_tandemRepeat_software/trgt/repeats/repeat_catalog.hg38.bed --threads 10 --reads /home/ljmills/ljmills/pacBio_tandemRepeat_software//HGSVC_samples/HG00732.sort.bam --output-prefix /home/ljmills/ljmills/pacBio_tandemRepeat_software//HGSVC_samples/HG00732.sort.fullRepeat

Thanks
-L

**Comment by egor-dolzhenko** [comment]
Hi Lauren. Thank you for reporting this issue. Could you please confirm that the latest version of TRGT (v0.3.4) still produces the error? And could you please generate the backtrace like so:

```
RUST_BACKTRACE=1 /home/ljmills/shared/bin/trgt-v0.3.4-linux_x86_64 --genome /home/ljmills/shared/hg38_clean/seq/hg38_clean.fa --repeats /home/ljmills/ljmills/pacBio_tandemRepeat_software/trgt/repeats/repeat_catalog.hg38.bed --threads 10 --reads /home/ljmills/ljmills/pacBio_tandemRepeat_software//HGSVC_samples/HG00732.sort.bam --output-prefix /home/ljmills/ljmills/pacBio_tandemRepeat_software//HGSVC_samples/HG00732.sort.fullRepeat
```

**Comment by ljmills** [comment]
I reran with the v0.3.4 and with the backtrace 

thread '<unnamed>' panicked at 'byte index 18446744073709551614 is out of bounds of `TGTGGCTTAGCATTCCAGCCTGGGTGACAAGAGCAAAACTCTGTCTCAAAATAAATAAATAAATAAATAAATAAATAAATAAATAAATTAATAAATAAATAAAATGTCCTCATGAAACACCTGTGGCTTAGCAGGAAGTTGGAAGCTAAAGAAGTGACCAGCGCCTGGAGTTTGGCTCCTGGCTGAATCCACATGGGCTCTTTGGTTCTTTCTTTCTTTCCCTGGAATAAGGATTCAAGGAGAATTTCTCCAATAG`[...]', library/core/src/str/mod.rs:107:9
stack backtrace:
   0: rust_begin_unwind
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panicking.rs:143:14
   2: core::str::slice_error_fail_rt
   3: core::ops::function::FnOnce::call_once
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/ops/function.rs:227:5
   4: core::intrinsics::const_eval_select
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/intrinsics.rs:2361:5
   5: core::str::slice_error_fail
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/str/mod.rs:86:9
   6: trgt::workflows::get_spanning::get_spanning
   7: trgt::workflows::tr::analyze
   8: <F as threadpool::FnBox>::call_box
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

**Comment by egor-dolzhenko** [comment]
Thank you! Would you be open to testing the fixed binary? If yes, perhaps we could connect by [email](mailto:edolzhenko@pacificbiosciences.com)?

**Comment by ljmills** [comment]
Happy to I will email you shortly

**Comment by egor-dolzhenko** [comment]
I will close this issue for now -- please let me know if you are still having this problem.
