### ISSUE TITLE
support for bgzipped catalogs

### ISSUE THREAD

**Issue by bw2** [PacificBiosciences/trgt#40]
For large catalogs, it would be nice if trgt genotype / validate commands could read a compressed BED file. 
Currently, they both exit immediately without generating an error.

**Comment by tmokveld** [comment]
By any chance, were these catalogs compressed using bgzip? It seems TRGT encountered problems with concatenated gzip streams, only processing the first BGZF block. This has been fixed and will be in the upcoming release.

Note that you can enable more verbose logging with the verbose flag, .e.g, `trgt -v genotype` or `trgt -vv genotype` for higher verbosity.

**Comment by bw2** [comment]
great, yes it was bgzipped

**Comment by tmokveld** [comment]
This has been fixed in [TRGT v1.2.0](https://github.com/PacificBiosciences/trgt/releases/tag/v1.2.0).
