### ISSUE TITLE
validate command should print something if a catalog passes validation

### ISSUE THREAD

**Issue by bw2** [PacificBiosciences/trgt#41]
Currently, the "validate" command completes without printing any log messages, making it hard to tell if there was a silent error (like with bgzipped catalogs), or if the catalog passed validation.

**Comment by tmokveld** [comment]
The output of `validate` is currently on the INFO level, so it only appears with a `-v` flag (`trgt -v validate`). However, you're right that it makes more sense for there to always be output with this command, will look into it.
