### ISSUE TITLE
thread 'main' panicked at 'assertion failed

### ISSUE THREAD

**Issue by Nehir291** [PacificBiosciences/trgt#5]
Hi,
I tried both trgt-v0.3.2 and trgt-v0.3.4 versions on Pacbio CCS bams aligned with minimap2.
However in both attempts I had this error message:

`thread 'main' panicked at 'assertion failed: name_and_value.len() == 2', src/locus.rs:50:5
stack backtrace:
   0: rust_begin_unwind
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panicking.rs:143:14
   2: core::panicking::panic
             at /rustc/fe5b13d681f25ee6474be29d748c65adcd91f69e/library/core/src/panicking.rs:48:5
   3: trgt::locus::decode
   4: trgt::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.`

How can I fix it?

I don't get the same error when I try trgt-v0.2.0, and I could collect outputs missing some STR loci with the error flag "Unable to locate flanking kmers for".

 Thank you!

**Comment by egor-dolzhenko** [comment]
Thank you for reporting the issue and apologies for the uninformative error message. The newer versions of TRGT use a different repeat catalog format. Could you please try using the latest [catalog](https://github.com/PacificBiosciences/trgt/tree/main/repeats)?

**Comment by Nehir291** [comment]
Thank you for the answer. It works fine now!
The initial error was due to the wrong catalog format.

**Comment by egor-dolzhenko** [comment]
Glad to hear it! Please reach out anytime if you run into any other issues.
