### ISSUE TITLE
Pathogenic repeats file

### ISSUE THREAD

**Issue by Madelinehazel** [PacificBiosciences/trgt#7]
Hi Egor, 

In the pathogenic repeats bed file, there is a [repeat annotated to gene NOTCH2NLC](https://github.com/PacificBiosciences/trgt/blob/main/repeats/pathogenic_repeats.hg38.bed#L2), and another to NOTCH2NL. The coordinates for the NOTCH2NLC repeat seem to map to NOTCH2NLA, and the coordinates for the NOTCH2NL repeat map to NOTCH2LNC. Is this a mixup or am I missing something?

Thank you!
Madeline

**Comment by egor-dolzhenko** [comment]
Hi Madeline. Thank you for catching this! I'll update the definitions.

**Comment by egor-dolzhenko** [comment]
I just updated the definitions -- do they look good to you?

**Comment by Madelinehazel** [comment]
Looks good to me, thank you!
